apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: filebeat-filebeat
    release: filebeat
  name: filebeat-filebeat
  namespace: default
secrets:
- name: filebeat-filebeat-token-fdwqz

