apiVersion: v1
data:
  filebeat.yml: |
    filebeat.inputs:
    - type: docker
      containers.ids:
      - '*'
      processors:
      - add_kubernetes_metadata: ~

    output.logstash:
      host: '${NODE_NAME}'
      hosts: 'logstash:5044'
kind: ConfigMap
metadata:
  labels:
    app: filebeat-filebeat
    release: filebeat
  name: filebeat-filebeat-config
  namespace: default


