apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: filebeat-filebeat
    release: filebeat
  name: filebeat-filebeat-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: filebeat-filebeat-cluster-role
subjects:
- kind: ServiceAccount
  name: filebeat-filebeat
  namespace: default

