apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-data-pv-claim
  namespace: team2
spec:
  storageClassName: local-storage 
  volumeName: postgresql-data-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
