apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-data-pv 
  namespace: team2
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/app/postgressql"
