apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
  namespace: team2
spec:
  serviceName: postgresql
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: database
                operator: In
                values:
                - database
      volumes:
      - name: postgresql-data-pvc
        persistentVolumeClaim:
          claimName: postgresql-data-pv-claim
      containers:
      - name: postgresql
        image: postgres:12.1
        imagePullPolicy: IfNotPresent
        env:
        - name: POSTGRES_USER
          value: admin
        - name: POSTGRES_PASSWORD
          value: welcome1.
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgresql-data-pvc
          mountPath: /var/lib/postgresql/data
      restartPolicy: Always

