apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: default
  labels:
    component: kibana
spec:
  selector:
    #component: kibana
    app: kibana
  ports:
  - name: http
    port: 80 
    targetPort: http
    nodePort: 30197
  type: NodePort
