apiVersion: v1
kind: Service
metadata:
  name: kafka-topics-ui
  namespace: default
spec:
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 31973
    protocol: TCP
  type: NodePort
  selector:
    app: kafka-topics-ui
