pipeline{
 agent any
 environment
 {
     dockerRegistry= 'http://localhost:8082'
 }
 stages
  {
      stage ('repository clone')
      {
          steps {
              /*git credentialsId: 'gitcreds', url: 'https://github.com/cassador/devops-docker.git'*/
              checkout scm
          }
      }
      /*stage ('source coude build')
      {
          steps {

          }
      }*/
      stage (' docker image build & push to repo')
      {
          steps{
              dir('centos-jdk8') {
                script {
                    sh 'ls -la'
                    /*docker.build("centos-jdk8")*/
                    /* adding for additional complex testing*/
                    docker.withRegistry('http://localhost:8082', 'nexus') {
                        def customImage = docker.build("centos-jdk8")
                        customImage.push()
                    }
                }
              }
          }
      }

  }
}
