apiVersion: v1
kind: Service
metadata:
  name: smp-activemq
  namespace: default
  labels:
    app: smp-activemq
spec:
  type: NodePort
  selector:
    app: smp-activemq
  ports:
  - nodePort: 32191
    port: 61616
    name: smp-activemq
    targetPort: 54321
