apiVersion: v1
kind: Service
metadata:
  name: smp-activemq-admin
  namespace: default
  labels:
    app: smp-activemq
spec:
  type: NodePort
  selector:
    app: smp-activemq
  ports:
  - nodePort: 32192
    port: 8161
    name: smp-activemq
