apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: activemq-pv-claim
spec:
  storageClassName: local-storage 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
