apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pv-claim-team2
  namespace: team2
spec:
  storageClassName: local-storage
  volumeName: redis-volume-team2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
