pipeline{
 agent any
 environment
 {
     dockerRegistry= 'http://localhost:8082'
     kubecredentials= "kubernetes-dev"
     credentials= 'nexus'
 }
 stages
  {
      stage ('repository clone')
      {
          steps {
              /*git credentialsId: 'gitcreds', url: 'https://github.com/cassador/devops-docker.git'*/
              checkout scm
          }
      }
      /*stage ('source coude build')
      {
          steps {

          }
      }*/
      stage (' docker image build & push to repo')
      {
          steps{
              dir('couchbase') {
                script {
                    sh 'ls -la'
                    /*docker.build("centos-jdk8")*/
                    /* adding for additional complex testing*/
                    docker.withRegistry('http://localhost:8082', credentials) {
                        def customImage = docker.build("couchbase:6.0.0")
                        customImage.push()
                    }
                }
              }
          }
      }
      stage ('kubernetes deploy')
      {
        steps {
            script {
              withCredentials([file(credentialsId: kubecredentials, variable: 'kubeconfig')]) {
                sh(script: 'kubectl apply -f cluster-master.yaml' + ' --kubeconfig $kubeconfig')
                }
              }
          }
      }

  }
}
