apiVersion: v1
kind: Service
metadata:
  name: logstash
  namespace: default
spec:
  ports:
  - port: 5044
    protocol: TCP
    targetPort: 5044
    nodePort: 31544
  selector:
    app: logstash
  sessionAffinity: None
  type: NodePort 
status:
  loadBalancer: {}

