kind: Service
apiVersion: v1
metadata:
  name: logstash
spec:
  type: NodePort
  selector:
    app: logstash
  ports:
  - protocol: TCP
    port: 5044
#    targetPort: 5044
    nodePort: 31544
#    name: filebeat
  - protocol: TCP
    port: 9600
    targetPort: 9600
    name: logstash
    ---

