---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: logstash
  namespace: default 
spec:
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash        
    spec:
      hostname: logstash
      containers:
      - name: logstash
        ports:
          - containerPort: 5044
            name: filebeat
          - containerPort: 9600
            name: logstash
        image: docker.elastic.co/logstash/logstash:7.4.2
#        volumeMounts:
#          - name: logstash-config
#            mountPath: /usr/share/logstash/pipeline/
#        command:
#        - logstash
      volumes:
      - name: logstash-config
        configMap:
          name: logstash-conf
---
kind: Service
apiVersion: v1
metadata:
  name: logstash
spec:
  type: NodePort
  selector:
    app: logstash
  ports:
  - protocol: TCP
    port: 5044
    targetPort: 5044
#    nodePort: 30102
#    name: filebeat
  - protocol: TCP
    port: 9600
    targetPort: 9600
    name: logstash
    ---

