kind: ConfigMap
apiVersion: v1
metadata:
  name: logstash-conf
  namespace: default
data:
  logstash.conf: |
    input {
        beats {
            port => "5044"
        }
    }
    output {
        elasticsearch {
            hosts => [ "elasticsearch:9200" ]
        }
    }


