kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: activemq-artemis-pvc
  labels:
    app: activemq-artemis
  annotations:
    volume.alpha.kubernetes.io/storage-class: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
