apiVersion: v1
kind: Service
metadata:
  annotations:
    # Exclude unready slave nodes from DNS
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "false"
  name: activemq-artemis-service-endpoint
spec:
  ports:
  - name: tcp 
    port: 61616
    targetPort: 61616
  type: NodePort
  selector:
    app: activemq-artemis

