apiVersion: v1
kind: Service
metadata:
  annotations:
    # Exclude unready slave nodes from DNS
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "false"
  name: activemq-artemis-service-ui
spec:
  ports:
  - name: http
    port: 8161
    targetPort: 8161 
  type: NodePort
  selector:
    app: activemq-artemis
