apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pv-claim
spec:
  storageClassName: local-storage
  volumeName: redis-volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
