apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
#    version: __VERSION__
  name: redis
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30118
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis
  type: NodePort
