apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: redis
  name: redis
  namespace: default
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: redis
  serviceName: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: redis-pv-claim
#        - name: config
#          configMap:
#            name: redis-server-config
      imagePullSecrets:
        - name: regcred
      containers:
       - command:
           - redis-server
           - "--requirepass !rise^app1"
#        - "/redis-master/redis.conf"
         image: redis:4.0.10-stretch
        #image: localhost:8082/pdi/redis:1.0.0
         imagePullPolicy: IfNotPresent
         name: redis-sts
         ports:
         - containerPort: 6379
#           name: redis
#           protocol: TCP
         resources: {}
         volumeMounts:
         - mountPath: /data/
           name: data
#         - mountPath: /redis-master
#           name: config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 60
  updateStrategy:
    type: OnDelete

